// Generated by CoffeeScript 1.9.3

/* Configuration Variables
    confg.username: Your Web Services Username. This can be found in the Admin Console
    config.secret: Your Web Services Secret. This can also be found in the Admin Console
    config.reportSuite: The report suite you want to call the data from
    config.endpoint: The endpoint you will be hitting
 */
window.Realtime = {
  Models: {},
  Collections: {},
  Components: {}
};

Realtime.config = {
  username: "ammar.haider:Experian Interactive",
  secret: "b46a6131b46ec17eb3b3adcf7cb4405e",
  reportSuite: "expiukexperiancreditprod",
  endpoint: "api.omniture.com",
  method: 'Report.Run',
  interval: 10000
};
