// Generated by CoffeeScript 1.9.3
(function() {
  var container, div, h6, insert, p, ref;
  ref = React.DOM, p = ref.p, h6 = ref.h6, div = ref.div;
  container = $('.timer-div')[0];
  insert = React.createElement;
  Realtime.Components.timer = React.createClass({
    getInitialState: function() {
      return {
        dateNow: '',
        timeNow: ''
      };
    },
    render: function() {
      return div({}, p({
        className: 'text-muted'
      }, this.state.dateNow), h6({
        className: 'time-text'
      }, this.state.timeNow));
    },
    tick: function() {
      var date, day, time;
      day = moment().format('dddd');
      date = moment().format('MMMM Do YYYY');
      time = moment().format('h:mm:ss a');
      return this.setState({
        dateNow: day + ", " + date,
        timeNow: "" + time
      });
    },
    componentDidMount: function() {
      return this.interval = setInterval(this.tick, 1000);
    }
  });
  return React.render(insert(Realtime.Components.timer, null), container);
})();
